services:
  frontend:
    command: npm run dev -- --host --port 5173
    volumes:
      - ./frontend:/app
      - /app/node_modules

  backend:
    command: npm run dev
    volumes:
      - ./backend:/app
      - /app/node_modules